import type { IClass } from "@/types/IClassTypes";

export const MOCK_CLASSES: IClass[] = [
  {
    id: "class_grade_6",
    name: "Grade 6",
    createdAt: "2024-05-01T10:00:00.000Z",
    sections: [
      {
        id: "sec_6a",
        name: "A",
        teacher: "Ms. Priya Sharma",
        studentCount: 38,
        status: "active",
      },
      {
        id: "sec_6b",
        name: "B",
        teacher: "Mr. Rahul Verma",
        studentCount: 36,
        status: "active",
      },
      {
        id: "sec_6c",
        name: "C",
        teacher: "Ms. Anjali Mehta",
        studentCount: 40,
        status: "active",
      },
      {
        id: "sec_6d",
        name: "D",
        teacher: "Mr. Suresh Patel",
        studentCount: 35,
        status: "active",
      },
      {
        id: "sec_6e",
        name: "E",
        teacher: "Ms. Kavita Nair",
        studentCount: 37,
        status: "active",
      },
      {
        id: "sec_6f",
        name: "F",
        teacher: "Mr. Amit Joshi",
        studentCount: 39,
        status: "active",
      },
    ],
  },
  {
    id: "class_grade_7",
    name: "Grade 7",
    createdAt: "2024-05-02T10:00:00.000Z",
    sections: [
      {
        id: "sec_7a",
        name: "A",
        teacher: "Ms. Neha Gupta",
        studentCount: 34,
        status: "active",
      },
      {
        id: "sec_7b",
        name: "B",
        teacher: "Mr. Vikram Singh",
        studentCount: 32,
        status: "active",
      },
      {
        id: "sec_7c",
        name: "C",
        teacher: "Ms. Pooja Reddy",
        studentCount: 36,
        status: "active",
      },
      {
        id: "sec_7d",
        name: "D",
        teacher: "Mr. Arjun Kapoor",
        studentCount: 33,
        status: "active",
      },
      {
        id: "sec_7e",
        name: "E",
        teacher: "Ms. Sneha Iyer",
        studentCount: 35,
        status: "active",
      },
    ],
  },
  {
    id: "class_grade_8",
    name: "Grade 8",
    createdAt: "2024-05-03T10:00:00.000Z",
    sections: [
      {
        id: "sec_8a",
        name: "A",
        teacher: "Mr. Deepak Rao",
        studentCount: 40,
        status: "active",
      },
      {
        id: "sec_8b",
        name: "B",
        teacher: "Ms. Ritu Malhotra",
        studentCount: 38,
        status: "active",
      },
      {
        id: "sec_8c",
        name: "C",
        teacher: "Mr. Nikhil Das",
        studentCount: 37,
        status: "active",
      },
      {
        id: "sec_8d",
        name: "D",
        teacher: "Ms. Shreya Banerjee",
        studentCount: 39,
        status: "active",
      },
    ],
  },
  {
    id: "class_grade_9",
    name: "Grade 9",
    createdAt: "2024-05-04T10:00:00.000Z",
    sections: [
      {
        id: "sec_9a",
        name: "A",
        teacher: "Ms. Ananya Krishnan",
        studentCount: 42,
        status: "active",
      },
      {
        id: "sec_9b",
        name: "B",
        teacher: "Mr. Farhan Ali",
        studentCount: 41,
        status: "active",
      },
      {
        id: "sec_9c",
        name: "C",
        teacher: "Ms. Divya Menon",
        studentCount: 40,
        status: "active",
      },
    ],
  },
  {
    id: "class_grade_10",
    name: "Grade 10",
    createdAt: "2024-05-05T10:00:00.000Z",
    sections: [
      {
        id: "sec_10a",
        name: "A",
        teacher: "Mr. Rohan Desai",
        studentCount: 45,
        status: "active",
      },
      {
        id: "sec_10b",
        name: "B",
        teacher: "Ms. Ishita Bose",
        studentCount: 44,
        status: "active",
      },
    ],
  },
];
